"""add users

Revision ID: 029656c27efa
Revises: 915a9e0cf92d
Create Date: 2021-11-28 13:22:19.626209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '029656c27efa'
down_revision = '915a9e0cf92d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sleepsessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sleep_start', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sleep_end', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sleep_length', sa.Interval(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sleepsession')
    op.add_column('babies', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'babies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'babies', type_='foreignkey')
    op.drop_column('babies', 'user_id')
    op.create_table('sleepsession',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sleep_start', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('sleep_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('baby_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sleep_length', postgresql.INTERVAL(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], name='sleepsession_baby_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sleepsession_pkey')
    )
    op.drop_table('sleepsessions')
    op.drop_table('users')
    # ### end Alembic commands ###
