"""fixed cascade delete error

Revision ID: 1e6447502c16
Revises: 75f5d7e203fa
Create Date: 2021-11-29 17:07:54.110095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6447502c16'
down_revision = '75f5d7e203fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feeds', 'baby_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sleeps', 'baby_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sleeps', 'baby_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('feeds', 'baby_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
