"""update sleepsession

Revision ID: 328d268973e2
Revises: 49e2b3818910
Create Date: 2021-12-07 17:14:47.175057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328d268973e2'
down_revision = '49e2b3818910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
