"""sleep length to interval- deleted and replaced

Revision ID: 54e17f4bb16c
Revises: 7a826e04eaac
Create Date: 2021-11-27 23:54:47.489334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e17f4bb16c'
down_revision = '7a826e04eaac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleepsession', sa.Column('sleep_length', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sleepsession', 'sleep_length')
    # ### end Alembic commands ###
