"""sleep length to interval - again

Revision ID: 5c3781a09c6a
Revises: 8fcc28c12107
Create Date: 2021-11-27 23:52:32.961538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3781a09c6a'
down_revision = '8fcc28c12107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
