"""Added weights and temperatures

Revision ID: 6fbcf983b2f7
Revises: 1e6447502c16
Create Date: 2021-11-30 15:38:40.312557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbcf983b2f7'
down_revision = '1e6447502c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weights')
    op.drop_table('temperatures')
    # ### end Alembic commands ###
