"""sleep length to interval - again

Revision ID: 7a826e04eaac
Revises: 5c3781a09c6a
Create Date: 2021-11-27 23:53:32.253480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a826e04eaac'
down_revision = '5c3781a09c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sleepsession', 'sleep_length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleepsession', sa.Column('sleep_length', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
