"""added nappies

Revision ID: 8dbeabce125e
Revises: b43fc12687bc
Create Date: 2021-12-13 17:51:16.050791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbeabce125e'
down_revision = 'b43fc12687bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nappies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nappy_type', sa.Enum('wee', 'poo', 'wee_poo', name='nappy'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nappies')
    # ### end Alembic commands ###
