"""sleep length to interval

Revision ID: 8fcc28c12107
Revises: 648a6eed5428
Create Date: 2021-11-27 23:49:54.621081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcc28c12107'
down_revision = '648a6eed5428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
