"""add feed sessions

Revision ID: 915a9e0cf92d
Revises: 54e17f4bb16c
Create Date: 2021-11-28 11:29:58.963003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915a9e0cf92d'
down_revision = '54e17f4bb16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedsessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_start', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('feed_end', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('feed_length', sa.Interval(), nullable=True),
    sa.Column('baby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedsessions')
    # ### end Alembic commands ###
